### ISSUE TITLE
Unable to get the resolved type of class ResolvedReferenceType from T

### ISSUE THREAD

**Issue by deadlocklogic** [javaparser/javaparser#3184]
```java
@Test
public void test() {
    ParserConfiguration config = new ParserConfiguration();
    config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
    StaticJavaParser.setConfiguration(config);
    String s = "public class Program {\n" +
            "\n" +
            "    public static class InnerClass<T> {\n" +
            "       void method() {\n" +
            "           new InnerClass<T>();\n" + // Buggy
            "       }\n" +
            "    }\n" +
            "}";
    CompilationUnit cu = StaticJavaParser.parse(s);
    List<ObjectCreationExpr> objCrtExprs = cu.findAll(ObjectCreationExpr.class);
    objCrtExprs.forEach(objCrtExpr -> {
        objCrtExpr.getType().getTypeArguments().ifPresent(typeArgs -> {
            assertEquals(typeArgs.size(), 1);
            typeArgs.forEach(typeArg -> {
                ResolvedType resType = typeArg.resolve();
                assertTrue(resType.isTypeVariable());
                assertEquals(resType.asTypeVariable().describe(), "T");
            });
        });
    });
}
```
Basically the bug appears when trying to resolve a type argument. I still have many tests which fail on this subject involving different resolution but I hope they will get resolved when this bug gets fixed.
Otherwise I will fill a separate issue.
I will try to submit a PR after some code analysis.
Thanks.

**Comment by deadlocklogic** [comment]
Actually the problem is pretty easy but the solution is kinda tricky because the API might need to change slightly.
Type arguments are stored as `ClassOrInterfaceType`, but when `ClassOrInterfaceType` are resolved they expect a `ResolvedReferenceType` or throw an `UnsupportedOperationException`.
https://github.com/javaparser/javaparser/blob/21928852fcb3e5509abf456ebd7106bcbb77c578/javaparser-core/src/main/java/com/github/javaparser/ast/type/ClassOrInterfaceType.java#L311-L314
https://github.com/javaparser/javaparser/blob/21928852fcb3e5509abf456ebd7106bcbb77c578/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/JavaSymbolSolver.java#L279-L287
But in reality they are resolved into `ResolvedTypeVariable` which is not a `ResolvedReferenceType` and hence the exception.
https://github.com/javaparser/javaparser/blob/21928852fcb3e5509abf456ebd7106bcbb77c578/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java#L677-L699
```
Any thoughts?
Thanks!

**Comment by deadlocklogic** [comment]
Actually, I was able to easily fix this issue but my solution is quite ugly.
I introduced a method in `Type` class:
```java
public ResolvedType resolveWithTypeArgument() {
    return getSymbolResolver().toResolvedType(this, ResolvedType.class);
}
```
and instead of calling `resolve` on type arguments now I call `resolveWithTypeArgument`, I know it is ugly but it works.
After searching the issue list a bit, I believe that this bug was reported before.
Any better solution?

**Comment by deadlocklogic** [comment]
Still this solution is naïve because it doesn't solve further issues like this next one which is kinda weird (Why the first test in method1 even passes!):
```java
@Test
public void test5() {
    ParserConfiguration config = new ParserConfiguration();
    config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
    StaticJavaParser.setConfiguration(config);

    String s = "public class Program {\n" +
            "\n" +
            "    public static class InnerClass<T> {\n" +
            "       void method1() {\n" +
            "           new InnerClass<T>();\n" + // Buggy
            "       }\n" +
            "       <T1> void method2() {\n" +
            "           new InnerClass<T1>();\n" + // OK
            "           new InnerClass<T>();\n" + // Buggy
            "       }\n" +
            "    }\n" +
            "}";

    CompilationUnit cu = StaticJavaParser.parse(s);
    List<ObjectCreationExpr> objCrtExprs = cu.findAll(ObjectCreationExpr.class);
    objCrtExprs.forEach(expr -> {
        ResolvedReferenceType resRefType = expr.getType().resolve();
        ResolvedReferenceTypeDeclaration resRefTypeDecl = resRefType.getTypeDeclaration().get();
        List<ResolvedTypeParameterDeclaration> resTypeParamsDecl = resRefTypeDecl.getTypeParameters();
        List<Pair<ResolvedTypeParameterDeclaration, ResolvedType>> resTypeParamsDeclMap = resRefType.getTypeParametersMap();
        assertFalse(resTypeParamsDecl.isEmpty());
        assertFalse(resTypeParamsDeclMap.isEmpty());
        for (Pair<ResolvedTypeParameterDeclaration, ResolvedType> resTypeParamsDeclPair : resTypeParamsDeclMap) {
            assertTrue(resTypeParamsDeclPair.b.isTypeVariable());
        }
    });
}
```

**Comment by jlerbsc** [comment]
Your first test case is no longer a problem in the current version of JP. Could you confirm that this issue is resolved?

**Comment by deadlocklogic** [comment]
Well to be honest, back then I was facing loads of issues with the `symbol-solver`.
And the priority of bug fixes wasn't for the solver but for the parser.
So I migrated to `IntellijIDEA` PSI API and created a plugin.

If someone is planning to improve the `symbol-solver` I can consider switching back to `javaparser`, because I prefer this project as I can easily create a CLI.
Thanks.

**Comment by jlerbsc** [comment]
Sorry for taking so long to respond. I will therefore close this issue because I no longer reproduce your problem. For the 2nd part of this issue, a new one should be created to better isolate the problem and ensure that it is reproducible with a more recent version of the project. I'm not sure this is an error.

I'm also interested in contributions that could improve how JP works.

**Comment by deadlocklogic** [comment]
Just a curious question.
Have you tried creating 2 tests and running them? If so the problem would be indeed solved.

Anyway, I still have an old project based on JP which I can revisit if the solver module is actively developed.

**Comment by jlerbsc** [comment]
I ran your first unit test without error. As for the second unit test, it doesn't seem to be an error in JP. The test actually fails because it doesn't seem to me to be properly developed. The error revolves around the notion of rawtype.

**Comment by deadlocklogic** [comment]
```java
public class Program {
    public static class InnerClass<T> {
        <T1> void method2() {
            new InnerClass<T1>(); // OK
            new InnerClass<T>(); // Buggy
        }
    }
}
```
The second example was trying to resolve an upper level generic parameter inside a generic method. which was failing.

**Comment by jlerbsc** [comment]
Can you create a specific issue because it's not quite the same problem.

**Comment by deadlocklogic** [comment]
No problem, when I have some time I will fetch back my old projects and open an issue.

**Comment by jlerbsc** [comment]
I think this issue is related to how JP determines if the type is a rawtype in ResolvedReferenceType class.

@ftomassetti Can you give me your opinion on how well isRawType() method works?

https://docs.oracle.com/javase/tutorial/java/generics/rawTypes.html

Below is the test case that raises this issue:

    @Test
    public void test5() {
    ParserConfiguration config = new ParserConfiguration();
    config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
    StaticJavaParser.setConfiguration(config);
    String s = "public class Program {\n" +
            "\n" +
            "    public static class InnerClass<T> {\n" +
            "       void method1() {\n" +
            "           new InnerClass<T>();\n" + // Buggy
            "       }\n" +
            "       <T1> void method2() {\n" +
            "           new InnerClass<T1>();\n" + // OK
            "           new InnerClass<T>();\n" + // Buggy
            "       }\n" +
            "    }\n" +
            "}";

    CompilationUnit cu = StaticJavaParser.parse(s);
    List<ObjectCreationExpr> objCrtExprs = cu.findAll(ObjectCreationExpr.class);
    objCrtExprs.forEach(expr -> {
        ResolvedReferenceType resRefType = expr.getType().resolve()..asReferenceType();
        ResolvedReferenceTypeDeclaration resRefTypeDecl = resRefType.getTypeDeclaration().get();
        List<ResolvedTypeParameterDeclaration> resTypeParamsDecl = resRefTypeDecl.getTypeParameters();
        List<Pair<ResolvedTypeParameterDeclaration, ResolvedType>> resTypeParamsDeclMap = resRefType.getTypeParametersMap();
        assertFalse(resTypeParamsDecl.isEmpty());
        assertFalse(resTypeParamsDeclMap.isEmpty());
        for (Pair<ResolvedTypeParameterDeclaration, ResolvedType> resTypeParamsDeclPair : resTypeParamsDeclMap) {
            assertTrue(resTypeParamsDeclPair.b.isTypeVariable());
        }
    });
    }

In my opinion the Program.InnerClass\<T\> type should not be considered as a rawtype.
