### ISSUE TITLE
`LexicalPreservingPrinter` does not print new `PrimitiveType`s

### ISSUE THREAD

**Issue by abextm** [javaparser/javaparser#4781]
`LexicalPreservingPrinter` can't print `PrimitiveType`s that it didn't also parse. 

`getOrCreateNodeText` eventually calls itself, so nothing ever fills in the `NodeText` that is allocated.
```java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.type.PrimitiveType;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

class Scratch
{
	public static void main(String[] args)
	{
		var config = new ParserConfiguration();
		config.setLexicalPreservationEnabled(true);

		var cu = new JavaParser(config).parse("class Foo {\n" +
				"}")
			.getResult()
			.get();

		LexicalPreservingPrinter.setup(cu);

		cu.getType(0).addField(PrimitiveType.intType(), "foo");

		System.out.println(LexicalPreservingPrinter.print(cu));
	}
}
```

Output:
```java
class Foo {

 foo;
}
```

Expected:

```java
class Foo {

int foo;
}
```

Version:
`3.27.0`

**Comment by jlerbsc** [comment]
Thank you for reporting this bug.

**Comment by jlerbsc** [comment]
There is a bug but for the moment you can simply remove this line which is useless in your case.

    config.setLexicalPreservationEnabled(true);

**Comment by jlerbsc** [comment]
This is a fairly complex bug to correct that was introduced with the latest version of JP, which includes the option of declaring the lexical printer as the default printer. It seems to be specific to adding dynamic code (versus parsed code). In this particular case the default printing mechanism is not initialised on the new node and this gives rise to the error you have seen.

**Comment by VKS1572** [comment]
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.type.PrimitiveType;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

public class Scratch {
    public static void main(String[] args) {
        var config = new ParserConfiguration();
        config.setLexicalPreservationEnabled(true);

        var parser = new JavaParser(config);

        var cu = parser.parse(
                "class Foo {\n" +
                "}"
        ).getResult().orElseThrow();

        // Enable lexical preservation
        LexicalPreservingPrinter.setup(cu);

        // Get class Foo
        ClassOrInterfaceDeclaration clazz =
                cu.getClassByName("Foo").orElseThrow();

        // Add field: int foo;
        clazz.addField(PrimitiveType.intType(), "foo");

        // Print updated code
        System.out.println(LexicalPreservingPrinter.print(cu));
    }
}

**Comment by jlerbsc** [comment]
This issue appears to have been resolved in a version currently under development.

**Comment by seokjun7410** [comment]
@jlerbsc

After further investigation, `setParentNode()` does not appear to be the root cause. The failure was caused by `PrimitiveType` re-entering LPP through `node.toString()` while its `NodeText` was still being initialized. The CSM-based refactoring resolves #4781, though a broader reentrancy-related risk may still exist in LPP.

**Comment by jlerbsc** [comment]
If the issue has been resolved, there is no particular reason to reopen this issue or make any further changes to the project. Do you have a specific test case to submit?

**Comment by seokjun7410** [comment]
I did not intend to propose broader LPP architecture changes. I was asking from a follow-up maintenance perspective.

My concern is that if future LPP-related code tries to produce output through a `toString()` path while `NodeText` is being initialized, the same kind of bug could occur again.
